config/routes.rb
Polcomp::Application.routes.draw do

  resources :proprietaries

  get "mainforms/showsessions" => "mainforms#showsessions", :as => "showsessions"  
  get "mainforms/showusers" => "mainforms#showusers", :as => "showusers"
  
  get "mainforms/showsessions" => "mainforms#showsessions", :as => "showsessions"
  get "mainforms/code401" => "mainforms#code401"
  get "mainform/new" => "mainform#new", :as => "mainform_new"
  get "mainform/show" => "mainform#show", :as => "show"
  get "mainforms/mainpage" => "mainforms#mainpage", :as => "mainpage"

  get "forms/search" => "forms#search", :as => "search"
  get "forms/searchForms" => "forms#searchForms"
  get 'forms/getFormDetails' => 'forms#getFormDetails', :as => "getFormDetails"
  get 'forms/checkoutForm' => 'forms#checkoutForm'
  get 'forms/copyForm' => 'forms#copyForm'
  get 'forms/excelDownload' => 'forms#excelDownload'
  get 'forms/generateReport' => 'forms#generateReport', :as => "generateReport"
  get 'forms/createForm' => 'forms#createForm', :as => :createForm
  post 'forms/updateForm' => 'forms#updateForm', :as => :updateForm
  post 'forms/unlockedForm' => 'forms#unlockedForm', :as => :unlockedForm
  get 'forms/:id/copy' => 'forms#copy'
  
  get 'sessions/new'
  get 'sessions/errorLogin' => 'sessions#errorLogin', :as => "errorLogin"
  post 'sessions/endSession' => "sessions#endSession"
  post 'sessions/destroy' => "sessions#destroy"

  get "users/new" => "users#new", :as => "adduser"
  
  get "homepage/index"  
  get "homepage/login"

  get "statuses/statusLists" => "statuses#statusLists"
  get 'statuses/getTrackingStatus' => 'statuses#getTrackingStatus'
  get 'statuses/createStatus' => 'statuses#createStatus'
  post 'statuses/updateTrackingStatus' => 'statuses#updateTrackingStatus'
  
  get "policy_types/policyTypeLists" => "policy_types#policyTypeLists" 
  get "policy_types/createPolicyType" => "policy_types#createPolicyType"
  get "policy_types/getPolicyType" => "policy_types#getPolicyType"
  post "policy_types/updatePolicyType" => "policy_types#updatePolicyType"  
  
  get "document_types/documentTypeLists" => "document_types#documentTypeLists" 
  get "document_types/createDocumentType" => "document_types#createDocumentType"
  get "document_types/getDocumentType" => "document_types#getDocumentType"
  post "document_types/updateDocumentType" => "document_types#updateDocumentType"
  
  get "submission_types/submissionTypeLists" => "submission_types#submissionTypeLists" 
  get "submission_types/createSubmissionType" => "submission_types#createSubmissionType"
  get "submission_types/getSubmissionType" => "submission_types#getSubmissionType"
  post "submission_types/updateSubmissionType" => "submission_types#updateSubmissionType"
  
  get "homepage/index"
  get "sessions/new"
  get "mainforms/showusers" => "mainforms#showusers", :as => "manageusers"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "homepage/index" => "homepage#index", :as => "home_page"  

  resources :users
  resources :sessions
  resources :mainforms
  resources :forms
	resources :locked_forms
  resources :document_types
  resources :policy_types
  resources :statuses
  resources :submission_types
  
  root :to => "homepage#index"

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
  
  def statusLists
    code = 403
    msg = "Forbidden"
    @statuses = {}
    
   
    ssnid = params[:ssnid]
    
    #sortColumn, sortAsc
    #To do session authentication
    if true
      if !params[:status].nil? && params[:status].length > 0
          @statuses = Status.where("lower(STATUS) like '%#{params[:status]}%'").order(params[:sortColumn] + ((params[:sortAsc] == "false") ? " DESC" : " ASC"))
      else
          #@statuses = Status.order(params[:sortColumn] + ((params[:sortAsc]== "true")? " ASC" : " DESC"));
          @statuses = Status.order(params[:sortColumn] + ((params[:sortAsc] == "false") ? " DESC" : " ASC"))
      end
      
      if @statuses.nil?
        code = 400
        msg = "Bad Reqeust"
      else
        code = 200
        msg = "Reqeust Successful"
      end
      
    else
       code = 401
       msg = "Not Authorized"
    end
    
    respond_to do |format|
      format.json { render json: {
          :params => params.except("controller", "action", "format"),
          :response => {
            :total_count => @statuses.count,
            :statuses => @statuses
          },
          :status => { :code => code, :message => msg}
        }
     }
    end
    
  end
  
  def getTrackingStatus
    code = 403
    msg = "Forbidden"
    @status = {}
    ssnid = params[:ssnid]
    
    #To do session authentication
    if Session.where("status = 'Active' and session_id = '#{ssnid}'").length > 0
      @status = Status.find(params[:status_id])
       if @status.nil?
        code = 400
        msg = "Bad Reqeust"
      else
        code = 200
        msg = "Reqeust Successful"
      end
    else
      code = 401
      msg = "Not Authorized" 
    end
    
    respond_to do |format|
      format.json { render json: {
          :params => params.except("controller", "action", "format"),
          :response => {
            :status => @status
          },
          :status => { :code => code, :message => msg }
        }
      }
    end
  end
  
  def updateTrackingStatus
    @status = Status.find(params[:status_id])
    ssnid = params[:ssnid]
    
    code = 200
    msg = "Success"
    
    respond_to do |format|
      if Session.where("status = 'Active' and session_id = '#{ssnid}'").length > 0
        if @status.update_attributes(params[:status])
           
           user = User.find(Session.find_by_session_id(params[:ssnid]).user_id)
           @status.updated_by = user.firstname + ' ' + user.lastname
           @status.updated_date = Time.now
           @status.save
           format.json { render json: {
                :params => params.except("controller", "action", "format"),
                :response => {
                    :status => @status
                },
                :status => { :code => code, :message => msg }
              }
           }
        else
            format.html { render action: "edit" }
            format.json { render json: {
                  :params => params.except("controller", "action", "format"),
                  :response => {
                    :status => @status
                  },
                  :status => { :code => 400, :message => @status.errors.messages }
                }
            }
        end
      else
        format.json { render json: {
              :params => params.except("controller", "action", "format"),
              :response => {
                :status => @status
              },
              :status => { :code => 401, :message => "Not Authorized" }
            }
        }
      end
    end
  end
  
  def createStatus
    
    @status = Status.new(params[:status])
    
    respond_to do |format|
      if Session.where("status = 'Active' and session_id = '#{params[:ssnid]}'").length > 0
        if @status.save 
          user = User.find(Session.find_by_session_id(params[:ssnid]).user_id) 
          @status.create_by = user.firstname + ' ' + user.lastname
          @status.create_date = Time.now
          @status.updated_by = user.firstname + ' ' + user.lastname
          @status.updated_date = Time.now
          @status.save
          #format.html { redirect_to edit_form_path(@form), notice: 'Form was successfully created.' }
          format.html{ head :no_content }
          #format.json { render json: @form, status: :created, location: @form }
          format.json { render json: {
              :params => params.except("controller", "action", "format"),
              :response => {
                :status => @status
              },
              :status => { :code => 200, :message => "Reqeust Successful" }
            } 
          }
        else
          format.html { render action: "new" }
          format.json { render json: {
              :params => params.except("controller", "action", "format"),
              :response => {
                :status => @status
              },
              :status => { :code => 400, :message => @status.errors.messages }
            }
          }
        end
      else
        format.json { render json: {
              :params => params.except("controller", "action", "format"),
              :response => {
                :status => {}
              },
              :status => { :code => 401, :message => "Not Authorized"  }
            }
          }
      end
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
	<div class="clearSpace10"></div>

      <div class="row">
        <div class="col-xs-6">
          <div class="row">
            <div class="form-group">
              <label class="col-xs-4">Status</label>
              <div class="col-xs-8">
                <input type="text" class="form-control" id="status_STATUS">
              </div>
            </div>
          </div>
          <div class="clearSpace10"></div>

        </div>

        <div class="col-xs-6"></div>
    </div>

app/views/statuses/edit.html.erb
<br />
<br />

<p id="notice">
	<% 
	if params[:jsAction] == "create" 
  		notice = "Status was successfully created"
  	elsif params[:jsAction] == "copy"
  		notice = "Status was successfully copied"
  	end 
  	%>
	<% if !notice.nil? && notice.length > 0%>
		<div class="alert alert-success alert-dismissable">
  			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  			<%= notice %>
		</div>
	<% end %>
</p>


<%= render 'form' %>

 <div class="row">
	<div class="form-group">
	  <div class="col-xs-2 hidden-xs">
	    &nbsp;
	  </div>
	  <div class="col-xs-2">
	    <button type="button" class="btn btn-default-cancel btn-sm btn-group-justified" onclick="window.location='/statuses';">Cancel</button>
	  </div>
	  <div class="col-xs-2">
	    <button type="button" class="btn btn-default-save btn-sm btn-group-justified" onclick="updateStatus(<%= params[:id] %>, '<%= session[:session_id] %>')">Save</button>
	  </div>
	  <div class="col-xs-6 hidden-xs">
	    &nbsp;
	  </div>
	</div>
 </div>
          
<br />
<br />
<script>
	$(document).ready(function(){
		processStatusData(<%= params[:id] %>, '<%= session[:session_id]%>');
	});
</script>

app/views/statuses/index.html.erb
<script>
	
	$(document).ready(function(){
		loadStatusList("<%= session[:session_id] %>");
	});
</script>

<!-- search bar -->
	<div class="row">
		<div class="col-xs-12">
			&nbsp;
			<div class="container">
			<form class="form-inline" role="form">
				<div class="row srch-bg-color" style="border-radius:6px;">
					<div class="col-xs-4">
						<div class="form-group">
							<div class="input-group input-group-sm">
								<span class="input-group-addon">Search Status</span>
								<input type="text" class="form-control" id="searchVal">  
			                </div>
			            </div>
					</div>
					<div class="col-xs-5">
	  					<div class="form-group">
							<button type="button" class="btn btn-sm btn-default col-lg-12 btn-search-color" onclick="loadStatusList()">Search</button>
						</div>
					</div>
					<div class="col-xs-3">
					</div>
				</div>
			</form>
			</div>
		</div>
	</div>
<!-- search bar -->

<br />

<div class="container" style="border-radius:6px; background-color:#E2E9F5;">
	<div class="row">
		<div id="statusResults" class="container">
		</div>	
	</div>
</div>

<br />

app/views/statuses/new.html.erb
<br />

<p id="notice"></p>

<%= render 'form' %>

<div class="row">
	<div class="form-group">
	  <div class="col-xs-2 hidden-xs">
	    &nbsp;
	  </div>
	  <div class="col-xs-2">
	    <button type="button" class="btn btn-default-cancel btn-sm btn-group-justified" onclick="window.location='/statuses';">Cancel</button>
	  </div>
	  <div class="col-xs-2">
	    <button type="button" class="btn btn-default-save btn-sm btn-group-justified" onclick="createStatus('<%= session[:session_id] %>')">Save</button>
	  </div>
	  <div class="col-xs-6 hidden-xs">
	    &nbsp;
	  </div>
	</div>
 </div>
 

<br />

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @status.STATUS %>
</p>

<p>
  <b>Create date:</b>
  <%= @status.CREATE_DATE %>
</p>

<p>
  <b>Create by:</b>
  <%= @status.CREATE_BY %>
</p>

<p>
  <b>Updated date:</b>
  <%= @status.UPDATED_DATE %>
</p>

<p>
  <b>Updated by:</b>
  <%= @status.UPDATED_BY %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>