config/routes.rb
Polcomp::Application.routes.draw do

  resources :proprietaries

  get "mainforms/showsessions" => "mainforms#showsessions", :as => "showsessions"  
  get "mainforms/showusers" => "mainforms#showusers", :as => "showusers"
  
  get "mainforms/showsessions" => "mainforms#showsessions", :as => "showsessions"
  get "mainforms/code401" => "mainforms#code401"
  get "mainform/new" => "mainform#new", :as => "mainform_new"
  get "mainform/show" => "mainform#show", :as => "show"
  get "mainforms/mainpage" => "mainforms#mainpage", :as => "mainpage"

  get "forms/search" => "forms#search", :as => "search"
  get "forms/searchForms" => "forms#searchForms"
  get 'forms/getFormDetails' => 'forms#getFormDetails', :as => "getFormDetails"
  get 'forms/checkoutForm' => 'forms#checkoutForm'
  get 'forms/copyForm' => 'forms#copyForm'
  get 'forms/excelDownload' => 'forms#excelDownload'
  get 'forms/generateReport' => 'forms#generateReport', :as => "generateReport"
  get 'forms/createForm' => 'forms#createForm', :as => :createForm
  post 'forms/updateForm' => 'forms#updateForm', :as => :updateForm
  post 'forms/unlockedForm' => 'forms#unlockedForm', :as => :unlockedForm
  get 'forms/:id/copy' => 'forms#copy'
  
  get 'sessions/new'
  get 'sessions/errorLogin' => 'sessions#errorLogin', :as => "errorLogin"
  post 'sessions/endSession' => "sessions#endSession"
  post 'sessions/destroy' => "sessions#destroy"

  get "users/new" => "users#new", :as => "adduser"
  
  get "homepage/index"  
  get "homepage/login"

  get "statuses/statusLists" => "statuses#statusLists"
  get 'statuses/getTrackingStatus' => 'statuses#getTrackingStatus'
  get 'statuses/createStatus' => 'statuses#createStatus'
  post 'statuses/updateTrackingStatus' => 'statuses#updateTrackingStatus'
  
  get "policy_types/policyTypeLists" => "policy_types#policyTypeLists" 
  get "policy_types/createPolicyType" => "policy_types#createPolicyType"
  get "policy_types/getPolicyType" => "policy_types#getPolicyType"
  post "policy_types/updatePolicyType" => "policy_types#updatePolicyType"  
  
  get "document_types/documentTypeLists" => "document_types#documentTypeLists" 
  get "document_types/createDocumentType" => "document_types#createDocumentType"
  get "document_types/getDocumentType" => "document_types#getDocumentType"
  post "document_types/updateDocumentType" => "document_types#updateDocumentType"
  
  get "submission_types/submissionTypeLists" => "submission_types#submissionTypeLists" 
  get "submission_types/createSubmissionType" => "submission_types#createSubmissionType"
  get "submission_types/getSubmissionType" => "submission_types#getSubmissionType"
  post "submission_types/updateSubmissionType" => "submission_types#updateSubmissionType"
  
  get "homepage/index"
  get "sessions/new"
  get "mainforms/showusers" => "mainforms#showusers", :as => "manageusers"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "homepage/index" => "homepage#index", :as => "home_page"  

  resources :users
  resources :sessions
  resources :mainforms
  resources :forms
	resources :locked_forms
  resources :document_types
  resources :policy_types
  resources :statuses
  resources :submission_types
  
  root :to => "homepage#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  self.table_name = "ADV_PO_USERS"
  attr_accessible :lastname, :firstname, :middlename, :department, :email, :usertype, :username, :password_hash, :password_salt, :status, :create_date, :create_by, :updated_date, :updated_by, :isActive

  attr_accessible :password_hash
  before_save :encrypt_password
  
  validates_confirmation_of :password_hash
  validates_presence_of :password_hash, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  
  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user      
    else
      nil
    end
  end
  
  def encrypt_password
    if password_hash.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password_hash, password_salt)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def adduser
	end

  def cancel
  end
  
	def new
  		@user = User.new
 	end

  def initial
    self[0,1]
  end

 	def create
  		@user = User.new(params[:user])
   		if @user.save
    		redirect_to showusers_url, :notice => "Signed up!"
   		else
    		render "new"
   		end
 	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %> 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <!-- <div class="form-holder-med" style="height:365px;">
    <div class="form-data-container" style="height:32px;">
      <div class="formTitle" style="height:100%;width:20%;"><div class="hasMarginTop">New Account</div></div>
      <div style="height:100%;width:80%;float:right;border-bottom:1px solid #75AAFA;">&nbsp;</div>--><!--DDEEFF-->
<!--      <div class="clearSpace30">&nbsp;</div>
      <div class="formPageStyle" style="height:290px;">&nbsp;-->


        
       
<div class="clearSpace20"></div>

 <!-- hidden fields -->
        <%= f.text_field :status, :class=>'txtbox2', :value=>'Active', :style=>"display:none" %>
        <%= f.text_field :create_date, :class=>'txtbox2', :value=>Time.now.strftime("%Y-%m-%d"), :style=>"display:none" %>
        <%= f.text_field :create_by, :class=>'txtbox2', :value=>((current_user.nil?) ? "Melgar G" : current_user.firstname + " " + current_user.lastname[0,1]), :style=>"display:none" %>
        <%= f.text_field :updated_date, :class=>'txtbox2', :value=>Time.now.strftime("%Y-%m-%d"), :style=>"display:none" %>
        <%= f.text_field :updated_by, :class=>'txtbox2', :value=>((current_user.nil?) ? "Melgar G" : current_user.firstname + " " + current_user.lastname[0,1]), :style=>"display:none" %>
        <%= f.text_field :isActive, :class=>'txtbox2', :value=>"1", :style=>"display:none" %>
        <!-- hidden fields -->


<div class="container" style="border-radius:6px; background-color:#E2E9F5;">
  
<h3>Add New User Page</h3>

  <div class="row">

    <div class="clearSpace20"></div>
    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :Last_Name, :class=>'col-xs-4' %>
          <div class="col-xs-8">
            <%= f.text_field :lastname, :class=>'form-control', :tabindex=> 1 %>
          </div>
      </div>
    </div>

    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :Department, :class=>'col-xs-4' %>
          <div class="col-xs-8">
            <%= f.text_field :department, :class=>'form-control', :tabindex=> 6 %>
          </div>
        </div>
    </div>

  </div>

  <br />

  <div class="row">

    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :First_Name, :class=>'col-xs-4' %>
          <div class="col-xs-8">
            <%= f.text_field :firstname, :class=>'form-control', :tabindex=> 2 %>
          </div>
        </div>
    </div>

    <div class="col-xs-6">
        <div class="form-group">
          <%= f.label :"User Type", :class=>'col-xs-4' %>
            <div class="col-xs-8">
              <%= f.text_field :usertype, :class=>'form-control', :tabindex=> 7 %>
            </div>
        </div>
    </div>

  </div>

  <br />

  <div class="row">

    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :"Middle Name", :class=>'col-xs-4' %>
          <div class="col-xs-8">
            <%= f.text_field :middlename, :class=>'form-control', :tabindex=> 3 %>
          </div>
      </div>
    </div>

    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :password, :class=>'col-xs-4' %>
          <div class="col-xs-8">
            <%= f.text_field :password_hash, :class=>'form-control', :tabindex=> 8 %>
          </div>
      </div>
    </div>

  </div>

  <br />

  <div class="row">
  
    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :Email, :class=>'col-xs-4' %>
          <div class="col-xs-8">
            <%= f.text_field :email, :class=>'form-control', :tabindex=> 4 %>
          </div>
      </div>
    </div>

    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :password_salt, :class=>'col-xs-4' %>
        <div class="col-xs-8">
          <%= f.text_field :password_salt, :class=>'form-control', :tabindex=> 9 %>
        </div>
      </div>
    </div>

  </div>

  <br />

  <div class="row">

    <div class="col-xs-6">
      <div class="form-group">
        <%= f.label :Username, :class=>'col-xs-4' %>
          <div class="col-xs-8">
            <%= f.text_field :username, :class=>'form-control', :tabindex=> 5 %>
          </div>
      </div>
    </div>
  

    <div class="col-xs-6">
      <div class="form-group">
        &nbsp;
     </div>
    </div>

  </div>

  <br />

  <div class="row">
    
    <div class="col-xs-6">
      <div class="form-group">
        &nbsp;
     </div>
    </div>
  

    <div class="col-xs-6">
      <div class="form-group">
        <div class="col-xs-4"> 
          &nbsp;     
        </div>
      </div>
      <div class="col-xs-8">
        <div class="form-group">
          <div class="col-xs-6">
            <%= link_to "Go to List page", showusers_path, :class=>'col-xs-12 btn btn-default-cancel btn-sm btn-group-justified', :tabindex=> 11 %>
          </div>
          <div class="col-xs-6">
            <%= f.submit :value=>"Save", :class=>'col-xs-12 btn btn-default-save btn-sm btn-group-justified', :tabindex=> 10 %>
          </div>
        </div>
      </div>
    </div>

  </div>

  <br />

</div>
       
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password hash</th>
    <th>Password salt</th>
    <th>Email</th>
    <th>Status</th>
    <th>Create date</th>
    <th>Create by</th>
    <th>Updated date</th>
    <th>Updated by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password_hash %></td>
    <td><%= user.password_salt %></td>
    <td><%= user.email %></td>
    <td><%= user.status %></td>
    <td><%= user.create_date %></td>
    <td><%= user.create_by %></td>
    <td><%= user.updated_date %></td>
    <td><%= user.updated_by %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form'%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password hash:</b>
  <%= @user.password_hash %>
</p>

<p>
  <b>Password salt:</b>
  <%= @user.password_salt %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Status:</b>
  <%= @user.status %>
</p>

<p>
  <b>Create date:</b>
  <%= @user.create_date %>
</p>

<p>
  <b>Create by:</b>
  <%= @user.create_by %>
</p>

<p>
  <b>Updated date:</b>
  <%= @user.updated_date %>
</p>

<p>
  <b>Updated by:</b>
  <%= @user.updated_by %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>