config/routes.rb
Polcomp::Application.routes.draw do

  resources :proprietaries

  get "mainforms/showsessions" => "mainforms#showsessions", :as => "showsessions"  
  get "mainforms/showusers" => "mainforms#showusers", :as => "showusers"
  
  get "mainforms/showsessions" => "mainforms#showsessions", :as => "showsessions"
  get "mainforms/code401" => "mainforms#code401"
  get "mainform/new" => "mainform#new", :as => "mainform_new"
  get "mainform/show" => "mainform#show", :as => "show"
  get "mainforms/mainpage" => "mainforms#mainpage", :as => "mainpage"

  get "forms/search" => "forms#search", :as => "search"
  get "forms/searchForms" => "forms#searchForms"
  get 'forms/getFormDetails' => 'forms#getFormDetails', :as => "getFormDetails"
  get 'forms/checkoutForm' => 'forms#checkoutForm'
  get 'forms/copyForm' => 'forms#copyForm'
  get 'forms/excelDownload' => 'forms#excelDownload'
  get 'forms/generateReport' => 'forms#generateReport', :as => "generateReport"
  get 'forms/createForm' => 'forms#createForm', :as => :createForm
  post 'forms/updateForm' => 'forms#updateForm', :as => :updateForm
  post 'forms/unlockedForm' => 'forms#unlockedForm', :as => :unlockedForm
  get 'forms/:id/copy' => 'forms#copy'
  
  get 'sessions/new'
  get 'sessions/errorLogin' => 'sessions#errorLogin', :as => "errorLogin"
  post 'sessions/endSession' => "sessions#endSession"
  post 'sessions/destroy' => "sessions#destroy"

  get "users/new" => "users#new", :as => "adduser"
  
  get "homepage/index"  
  get "homepage/login"

  get "statuses/statusLists" => "statuses#statusLists"
  get 'statuses/getTrackingStatus' => 'statuses#getTrackingStatus'
  get 'statuses/createStatus' => 'statuses#createStatus'
  post 'statuses/updateTrackingStatus' => 'statuses#updateTrackingStatus'
  
  get "policy_types/policyTypeLists" => "policy_types#policyTypeLists" 
  get "policy_types/createPolicyType" => "policy_types#createPolicyType"
  get "policy_types/getPolicyType" => "policy_types#getPolicyType"
  post "policy_types/updatePolicyType" => "policy_types#updatePolicyType"  
  
  get "document_types/documentTypeLists" => "document_types#documentTypeLists" 
  get "document_types/createDocumentType" => "document_types#createDocumentType"
  get "document_types/getDocumentType" => "document_types#getDocumentType"
  post "document_types/updateDocumentType" => "document_types#updateDocumentType"
  
  get "submission_types/submissionTypeLists" => "submission_types#submissionTypeLists" 
  get "submission_types/createSubmissionType" => "submission_types#createSubmissionType"
  get "submission_types/getSubmissionType" => "submission_types#getSubmissionType"
  post "submission_types/updateSubmissionType" => "submission_types#updateSubmissionType"
  
  get "homepage/index"
  get "sessions/new"
  get "mainforms/showusers" => "mainforms#showusers", :as => "manageusers"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "homepage/index" => "homepage#index", :as => "home_page"  

  resources :users
  resources :sessions
  resources :mainforms
  resources :forms
	resources :locked_forms
  resources :document_types
  resources :policy_types
  resources :statuses
  resources :submission_types
  
  root :to => "homepage#index"

end

app/models/proprietary.rb
class Proprietary < ActiveRecord::Base
  self.table_name = "FORM_TRACKING_MEMBERSHIP"
  attr_accessible :KSQ_SEQ_NO, :MEMBERSHIP
end

app/controllers/proprietaries_controller.rb
class ProprietariesController < ApplicationController
  # GET /proprietaries
  # GET /proprietaries.json
  def index
    @proprietaries = Proprietary.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proprietaries }
    end
  end

  # GET /proprietaries/1
  # GET /proprietaries/1.json
  def show
    @proprietary = Proprietary.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proprietary }
    end
  end

  # GET /proprietaries/new
  # GET /proprietaries/new.json
  def new
    @proprietary = Proprietary.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proprietary }
    end
  end

  # GET /proprietaries/1/edit
  def edit
    @proprietary = Proprietary.find(params[:id])
  end

  # POST /proprietaries
  # POST /proprietaries.json
  def create
    @proprietary = Proprietary.new(params[:proprietary])

    respond_to do |format|
      if @proprietary.save
        format.html { redirect_to @proprietary, notice: 'Proprietary was successfully created.' }
        format.json { render json: @proprietary, status: :created, location: @proprietary }
      else
        format.html { render action: "new" }
        format.json { render json: @proprietary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proprietaries/1
  # PUT /proprietaries/1.json
  def update
    @proprietary = Proprietary.find(params[:id])

    respond_to do |format|
      if @proprietary.update_attributes(params[:proprietary])
        format.html { redirect_to @proprietary, notice: 'Proprietary was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proprietary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proprietaries/1
  # DELETE /proprietaries/1.json
  def destroy
    @proprietary = Proprietary.find(params[:id])
    @proprietary.destroy

    respond_to do |format|
      format.html { redirect_to proprietaries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proprietaries_helper.rb
module ProprietariesHelper
end

app/views/proprietaries/_form.html.erb
<%= form_for(@proprietary) do |f| %>
  <% if @proprietary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proprietary.errors.count, "error") %> prohibited this proprietary from being saved:</h2>

      <ul>
      <% @proprietary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :KSQ_SEQ_NO %><br />
    <%= f.number_field :KSQ_SEQ_NO %>
  </div>
  <div class="field">
    <%= f.label :MEMBERSHIP %><br />
    <%= f.text_field :MEMBERSHIP %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proprietaries/edit.html.erb
<h1>Editing proprietary</h1>

<%= render 'form' %>

<%= link_to 'Show', @proprietary %> |
<%= link_to 'Back', proprietaries_path %>

app/views/proprietaries/index.html.erb
<h1>Listing proprietaries</h1>

<table>
  <tr>
    <th>Ksq seq no</th>
    <th>Membership</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proprietaries.each do |proprietary| %>
  <tr>
    <td><%= proprietary.KSQ_SEQ_NO %></td>
    <td><%= proprietary.MEMBERSHIP %></td>
    <td><%= link_to 'Show', proprietary %></td>
    <td><%= link_to 'Edit', edit_proprietary_path(proprietary) %></td>
    <td><%= link_to 'Destroy', proprietary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Proprietary', new_proprietary_path %>

app/views/proprietaries/new.html.erb
<h1>New proprietary</h1>

<%= render 'form' %>

<%= link_to 'Back', proprietaries_path %>

app/views/proprietaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ksq seq no:</b>
  <%= @proprietary.KSQ_SEQ_NO %>
</p>

<p>
  <b>Membership:</b>
  <%= @proprietary.MEMBERSHIP %>
</p>


<%= link_to 'Edit', edit_proprietary_path(@proprietary) %> |
<%= link_to 'Back', proprietaries_path %>