config/routes.rb
Polcomp::Application.routes.draw do

  resources :proprietaries

  get "mainforms/showsessions" => "mainforms#showsessions", :as => "showsessions"  
  get "mainforms/showusers" => "mainforms#showusers", :as => "showusers"
  
  get "mainforms/showsessions" => "mainforms#showsessions", :as => "showsessions"
  get "mainforms/code401" => "mainforms#code401"
  get "mainform/new" => "mainform#new", :as => "mainform_new"
  get "mainform/show" => "mainform#show", :as => "show"
  get "mainforms/mainpage" => "mainforms#mainpage", :as => "mainpage"

  get "forms/search" => "forms#search", :as => "search"
  get "forms/searchForms" => "forms#searchForms"
  get 'forms/getFormDetails' => 'forms#getFormDetails', :as => "getFormDetails"
  get 'forms/checkoutForm' => 'forms#checkoutForm'
  get 'forms/copyForm' => 'forms#copyForm'
  get 'forms/excelDownload' => 'forms#excelDownload'
  get 'forms/generateReport' => 'forms#generateReport', :as => "generateReport"
  get 'forms/createForm' => 'forms#createForm', :as => :createForm
  post 'forms/updateForm' => 'forms#updateForm', :as => :updateForm
  post 'forms/unlockedForm' => 'forms#unlockedForm', :as => :unlockedForm
  get 'forms/:id/copy' => 'forms#copy'
  
  get 'sessions/new'
  get 'sessions/errorLogin' => 'sessions#errorLogin', :as => "errorLogin"
  post 'sessions/endSession' => "sessions#endSession"
  post 'sessions/destroy' => "sessions#destroy"

  get "users/new" => "users#new", :as => "adduser"
  
  get "homepage/index"  
  get "homepage/login"

  get "statuses/statusLists" => "statuses#statusLists"
  get 'statuses/getTrackingStatus' => 'statuses#getTrackingStatus'
  get 'statuses/createStatus' => 'statuses#createStatus'
  post 'statuses/updateTrackingStatus' => 'statuses#updateTrackingStatus'
  
  get "policy_types/policyTypeLists" => "policy_types#policyTypeLists" 
  get "policy_types/createPolicyType" => "policy_types#createPolicyType"
  get "policy_types/getPolicyType" => "policy_types#getPolicyType"
  post "policy_types/updatePolicyType" => "policy_types#updatePolicyType"  
  
  get "document_types/documentTypeLists" => "document_types#documentTypeLists" 
  get "document_types/createDocumentType" => "document_types#createDocumentType"
  get "document_types/getDocumentType" => "document_types#getDocumentType"
  post "document_types/updateDocumentType" => "document_types#updateDocumentType"
  
  get "submission_types/submissionTypeLists" => "submission_types#submissionTypeLists" 
  get "submission_types/createSubmissionType" => "submission_types#createSubmissionType"
  get "submission_types/getSubmissionType" => "submission_types#getSubmissionType"
  post "submission_types/updateSubmissionType" => "submission_types#updateSubmissionType"
  
  get "homepage/index"
  get "sessions/new"
  get "mainforms/showusers" => "mainforms#showusers", :as => "manageusers"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "homepage/index" => "homepage#index", :as => "home_page"  

  resources :users
  resources :sessions
  resources :mainforms
  resources :forms
	resources :locked_forms
  resources :document_types
  resources :policy_types
  resources :statuses
  resources :submission_types
  
  root :to => "homepage#index"

end

app/controllers/locked_forms_controller.rb
class LockedFormsController < ApplicationController
  # GET /locked_forms
  # GET /locked_forms.json
  def index
    @locked_forms = LockedForm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locked_forms }
    end
  end

  # GET /locked_forms/1
  # GET /locked_forms/1.json
  def show
    @locked_form = LockedForm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @locked_form }
    end
  end

  # GET /locked_forms/new
  # GET /locked_forms/new.json
  def new
    @locked_form = LockedForm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @locked_form }
    end
  end

  # GET /locked_forms/1/edit
  def edit
    @locked_form = LockedForm.find(params[:id])
  end

  # POST /locked_forms
  # POST /locked_forms.json
  def create
    @locked_form = LockedForm.new(params[:locked_form])

    respond_to do |format|
      if @locked_form.save
        format.html { redirect_to @locked_form, notice: 'Locked form was successfully created.' }
        format.json { render json: @locked_form, status: :created, location: @locked_form }
      else
        format.html { render action: "new" }
        format.json { render json: @locked_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locked_forms/1
  # PUT /locked_forms/1.json
  def update
    @locked_form = LockedForm.find(params[:id])

    respond_to do |format|
      if @locked_form.update_attributes(params[:locked_form])
        format.html { redirect_to @locked_form, notice: 'Locked form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @locked_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locked_forms/1
  # DELETE /locked_forms/1.json
  def destroy
    @locked_form = LockedForm.find(params[:id])
    @locked_form.destroy

    respond_to do |format|
      format.html { redirect_to locked_forms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/locked_forms_helper.rb
module LockedFormsHelper
end

app/views/locked_forms/_form.html.erb
<%= form_for(@locked_form) do |f| %>
  <% if @locked_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locked_form.errors.count, "error") %> prohibited this locked_form from being saved:</h2>

      <ul>
      <% @locked_form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :FORM_ID %><br />
    <%= f.number_field :FORM_ID %>
  </div>
  <div class="field">
    <%= f.label :USER_ID %><br />
    <%= f.number_field :USER_ID %>
  </div>
  <div class="field">
    <%= f.label :SESSION_ID %><br />
    <%= f.text_field :SESSION_ID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locked_forms/edit.html.erb
<h1>Editing locked_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @locked_form %> |
<%= link_to 'Back', locked_forms_path %>

app/views/locked_forms/index.html.erb
<h1>Listing locked_forms</h1>

<table>
  <tr>
    <th>Form id</th>
    <th>User id</th>
    <th>Session id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locked_forms.each do |locked_form| %>
  <tr>
    <td><%= locked_form.FORM_ID %></td>
    <td><%= locked_form.USER_ID %></td>
    <td><%= locked_form.SESSION_ID %></td>
    <td><%= link_to 'Show', locked_form %></td>
    <td><%= link_to 'Edit', edit_locked_form_path(locked_form) %></td>
    <td><%= link_to 'Destroy', locked_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Locked form', new_locked_form_path %>

app/views/locked_forms/new.html.erb
<h1>New locked_form</h1>

<%= render 'form' %>

<%= link_to 'Back', locked_forms_path %>

app/views/locked_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Form id:</b>
  <%= @locked_form.FORM_ID %>
</p>

<p>
  <b>User id:</b>
  <%= @locked_form.USER_ID %>
</p>

<p>
  <b>Session id:</b>
  <%= @locked_form.SESSION_ID %>
</p>


<%= link_to 'Edit', edit_locked_form_path(@locked_form) %> |
<%= link_to 'Back', locked_forms_path %>